[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_sqlite", "php82Extensions.bcmath", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.tokenizer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "touch database/database.sqlite",
    "chmod -R 775 storage bootstrap/cache database"
]

[start]
cmd = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
